services:
  - type: web
    name: docecho
    env: python
    buildCommand: |
      python -m pip install --upgrade pip setuptools wheel
      pip install -r requirements.txt --no-cache-dir
    startCommand: |
      # Create directory structure with proper permissions
      mkdir -p /opt/data/{static,uploads,output,temp}
      chmod -R 755 /opt/data
      # Copy static files if empty
      if [ -z "$(ls -A /opt/data/static)" ]; then
        cp -r app/static/* /opt/data/static/ 2>/dev/null || true
      fi
      # Start application
      gunicorn wsgi:app --timeout 120 --workers 2 --threads 2
    envVars:
      - key: FLASK_ENV
        value: production
      - key: DATABASE_URL
        value: postgresql://docechodatabase_user:WCsXQO7Hp0mmz9YpzyCF806BJ5ky7XDx@dpg-cubq1u2n91rc7395ulm0-a/docechodatabase
      - key: SENDGRID_API_KEY
        value: your_sendgrid_api_key
      - key: MAIL_DEFAULT_SENDER
        value: "Gabbi Pereira <gabbipereira03@gmail.com>"
      - key: JWT_SECRET
        value: your_jwt_secret
      - key: FLASK_SECRET_KEY
        value: your_flask_secret_key
    disk:
      name: data
      mountPath: /opt/data
      sizeGB: 1
